//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webforum.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForumDB : DbContext
    {
        public ForumDB()
            : base("name=ForumDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blacklist> blacklists { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<thread> threads { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
